###05-9-save-plots
#This section is intended to automatically save and output the plots included in "plot_list"

plot_list <-
  c(
    "NewFloorDensity",
    "LengthDensity",
    "MeanDepthDensity",
    "MeanDiameterDensity",
    "MeanVolumeDensity",
    
    "SpearmanNewFloorMeanDepth",
    "SpearmanNewFloorMeanDepthMain",
    "SpearmanNewFloorMeanDepthMainWall",
    "SpearmanNewFloorMeanDiameter",
    "SpearmanNewFloorMeanDiameterMain",
    "SpearmanNewFloorMeanDiameterMainWall",
    "SpearmanNewFloorMeanVolume",
    "SpearmanNewFloorMeanVolumeMain",
    "SpearmanNewFloorMeanVolumeMainWall",
    
    "SpearmanNewFloorDepthSD",
    "SpearmanNewFloorDepthSDMain",
    "SpearmanNewFloorDepthSDMainWall",
    "SpearmanNewFloorDiameterSD",
    "SpearmanNewFloorDiameterSDMain",
    "SpearmanNewFloorDiameterSDMainWall",
    "SpearmanNewFloorVolumeSD",
    "SpearmanNewFloorVolumeSDMain",
    "SpearmanNewFloorVolumeSDMainWall",
    
    "SpearmanLengthMeanDepth",
    "SpearmanLengthMeanDepthMain",
    "SpearmanLengthMeanDepthMainWall",
    "SpearmanLengthMeanDiameter",
    "SpearmanLengthMeanDiameterMain",
    "SpearmanLengthMeanDiameterMainWall",
    "SpearmanLengthMeanVolume",
    "SpearmanLengthMeanVolumeMain",
    "SpearmanLengthMeanVolumeMainWall",
    
    "SpearmanLengthDepthSD",
    "SpearmanLengthDepthSDMain",
    "SpearmanLengthDepthSDMainWall",
    "SpearmanLengthDiameterSD",
    "SpearmanLengthDiameterSDMain",
    "SpearmanLengthDiameterSDMainWall",
    "SpearmanLengthVolumeSD",
    "SpearmanLengthVolumeSDMain",
    "SpearmanLengthVolumeSDMainWall",
    
    "SpearmanDiameterDepth",
    "SpearmanDiameterDepthMain",
    "SpearmanDiameterDepthMainWall",
    
    "LengthDepthRatioM",
    "LengthDiameterRatioM",
    "LengthVolumeRatioM",
    "LengthDepthSDRatioM",
    "LengthDiameterSDRatioM",
    "LengthVolumeSDRatioM",
    "LengthDepthRatioMW",
    "LengthDiameterRatioMW",
    "LengthVolumeRatioMW",
    "LengthDepthSDRatioMW",
    "LengthDiameterSDRatioMW",
    "LengthVolumeSDRatioMW",
    
    "LengthDepthRatioHexM",
    "LengthDiameterRatioHexM",
    "LengthVolumeRatioHexM",
    "LengthDepthSDRatioHexM",
    "LengthDiameterSDRatioHexM",
    "LengthVolumeSDRatioHexM",
    "LengthDepthRatioHexMW",
    "LengthDiameterRatioHexMW",
    "LengthVolumeRatioHexMW",
    "LengthDepthSDRatioHexMW",
    "LengthDiameterSDRatioHexMW",
    "LengthVolumeSDRatioHexMW",
    
    "LengthDepthRatioDensityM",
    "LengthDiameterRatioDensityM",
    "LengthVolumeRatioDensityM",
    "LengthDepthSDRatioDensityM",
    "LengthDiameterSDRatioDensityM",
    "LengthVolumeSDRatioDensityM",
    "LengthDepthRatioDensityMW",
    "LengthDiameterRatioDensityMW",
    "LengthVolumeRatioDensityMW",
    "LengthDepthSDRatioDensityMW",
    "LengthDiameterSDRatioDensityMW",
    "LengthVolumeSDRatioDensityMW",
    
    "PithouseCounts1000Plot",
    "PithouseCounts1000Barplot",
    "PithouseCounts1000BarplotStack",
    "PithouseCounts1000BarplotStackAvg",
    "PithouseCounts1000BarplotStackAvgNoUK",
    "PithouseCounts1000BarplotSeries",
    "PithouseCounts1000BarplotSeriesAvg",
    "PithouseCounts1000BarplotSeriesAvgNoUK",
    "PithouseCounts1000LineType",
    "PithouseCounts1000KDE",
    "PithouseCounts1000HistogramKDE",
    
    "NewFloorPlot1000",
    "MeanDepthPlot1000",
    "MeanDiameterPlot1000",
    "MeanVolumePlot1000",
    "SDDepthPlot1000",
    "SDDiameterPlot1000",
    "SDVolumePlot1000",
    "PithouseLengthPlot1000",
    
    "NewFloorPlotCombined1000",
    "NewFloorPlotPit1000",
    "NewFloorPlotWall1000",    
    "NewFloorPlotMain1000",
    "NewFloorPlotMainWall1000", 
    "NewFloorPlotMirror1000",
    
    "LengthPlotCombined1000",
    "LengthPlotPit1000", 
    "LengthPlotWall1000",
    "LengthPlotMain1000", 
    "LengthPlotMainWall1000", 
    "LengthPlotMirror1000", 
    "LengthPlotMirror1000filter",
    
    "MeanDepthPlotMain1000",
    "MeanDepthPlotMainWall1000",   
    "SDDepthPlotMain1000",
    "SDDepthPlotMainWall1000",
    "MeanDiameterPlotMain1000",
    "MeanDiameterPlotMainWall1000",
    "SDDiameterPlotMain1000",
    "SDDiameterPlotMainWall1000",
    "MeanVolumePlotMain1000",
    "MeanVolumePlotMainWall1000",
    "SDVolumePlotMain1000",
    "SDVolumePlotMainWall1000",

    "NewFloorBoxPlotCombined1000",
    "NewFloorBoxPlotPit1000",
    "NewFloorBoxPlotWall1000",
    "NewFloorBoxPlotMain1000",
    "NewFloorBoxPlotMainWall1000",
    "NewFloorBoxPlotMirror1000",
    
    "LengthBoxPlotCombined1000",
    "LengthBoxPlotPit1000", 
    "LengthBoxPlotWall1000",
    "LengthBoxPlotMain1000", 
    "LengthBoxPlotMainWall1000", 
    "LengthBoxPlotMirror1000",
    "LengthPlotMirror1000filter",
    
    "skeletalhex519",
    "skeletalhex519density",
    "skeletalhex519_subfilter",
    "skeletalhex519density_subfilter",
    "skeletalhex519_subfilter2",
    "skeletalhex519density_subfilter2",

    "hexdatatotal",
    "hexdatapit",
    "hexdatawall",
    "hexdatamain",
    "hexdatamainwall",
    "hexdatamirror",
    
    "hexdatatotalscale",
    "hexdatapitscale",
    "hexdatawallscale",
    "hexdatamainscale",
    "hexdatamainwallscale",
    "hexdatamirrorscale",
    
    "hexdatatotaldensity",
    "hexdatapitdensity",
    "hexdatawalldensity",
    "hexdatamaindensity",
    "hexdatamainwalldensity",
    "hexdatamirrordensity",
    
    "hexdatatotaldepth",
    "hexdatamaindepth",
    "hexdatamainwalldepth",
    "hexdatatotaldepthscale",
    "hexdatamaindepthscale",
    "hexdatamainwalldepthscale",
    "hexdatatotaldensitydepth",
    "hexdatamaindensitydepth",
    "hexdatamainwalldensitydepth",
    
    "hexdatatotaldiameter",
    "hexdatamaindiameter",
    "hexdatamainwalldiameter",
    "hexdatatotaldiameterscale",
    "hexdatamaindiameterscale",
    "hexdatamainwalldiameterscale",
    "hexdatatotaldensitydiameter",
    "hexdatamaindensitydiameter",
    "hexdatamainwalldensitydiameter",
    
    "hexdatatotalvolume",
    "hexdatamainvolume",
    "hexdatamainwallvolume",
    "hexdatatotalvolumescale",
    "hexdatamainvolumescale",
    "hexdatamainwallvolumescale",
    "hexdatatotaldensityvolume",
    "hexdatamaindensityvolume",
    "hexdatamainwalldensityvolume",
    
    "hexdatatotaldepthSD",
    "hexdatamaindepthSD",
    "hexdatamainwalldepthSD",
    "hexdatatotaldepthscaleSD",
    "hexdatamaindepthscaleSD",
    "hexdatamainwalldepthscaleSD",
    "hexdatatotaldensitydepthSD",
    "hexdatamaindensitydepthSD",
    "hexdatamainwalldensitydepthSD",
    
    "hexdatatotaldiameterSD",
    "hexdatamaindiameterSD",
    "hexdatamainwalldiameterSD",
    "hexdatatotaldiameterscaleSD",
    "hexdatamaindiameterscaleSD",
    "hexdatamainwalldiameterscaleSD",
    "hexdatatotaldensitydiameterSD",
    "hexdatamaindensitydiameterSD",
    "hexdatamainwalldensitydiameterSD",
    
    "hexdatatotalvolumeSD",
    "hexdatamainvolumeSD",
    "hexdatamainwallvolumeSD",
    "hexdatatotalvolumescaleSD",
    "hexdatamainvolumescaleSD",
    "hexdatamainwallvolumescaleSD",
    "hexdatatotaldensityvolumeSD",
    "hexdatamaindensityvolumeSD",
    "hexdatamainwalldensityvolumeSD",
    
    "PithouseLengthSumBarplotSeries",
    "PithouseLengthMeanBarplotSeries",
    "PithouseLengthSumBarplotSeriesfilter",
    "PithouseLengthMeanBarplotSeriesfilter",

    "LengthPlotPitCompare"
  )

for(i in 1:length(plot_list)) {
  # print(paste0("now saving ", plot_list[i]))
  ggsave(filename=here::here(sprintf("figures/%s.pdf", plot_list[i])),
         plot=get(plot_list[i]))
}
